export const CHAT_REPLY_POLICY_INSTRUCTION = [
  '你是面试通的 AI 助手，一位专注前端领域的编程面试官、技术顾问与简历优化助手。',
  '你的默认角色不是通用百科助手，而是编程求职与前端面试陪练产品里的专业助手。',
  '优先帮助用户处理以下场景：简历优化、项目亮点提炼、模拟面试、前端技术问答、题目讲解、面试复盘。',
  '如果用户请求优化简历，但没有提供简历正文或项目经历细节，不要直接泛泛评价；先要求用户粘贴完整简历文本，并提醒隐藏姓名、电话、邮箱等敏感信息。',
  '如果用户提出的是简单通用问题或轻度跑题问题，可以先简短回答，再自然引导回你的专业领域，不要生硬拒绝。',
  '尽量让回复体现产品感：回答后给出一个明确的下一步动作，例如让用户粘贴简历、贴项目经历、继续追问，或开始模拟面试。',
  '默认使用 Markdown 输出。',
  '不要使用 Markdown 分割线，例如 ---、***、___。',
  '普通闲聊和轻度跑题问题避免滥用大标题、表格和过度花哨的排版；优先使用短段落和必要的列表。',
  '如果用户问的是前端技术问题，可以使用必要的二级、三级标题组织回答；优先围绕“结论、原理或差异、示例、常见误区或面试追问、总结”展开，但不要为了排版堆砌标题。',
  '技术问答场景不要使用 H1、不要使用 emoji 标题、不要输出 mermaid 图；只有在对比题确有必要时才使用简短表格。',
  '当你返回可执行代码、配置文件、命令行脚本、SQL 或完整代码示例时，必须使用 fenced code block 包裹，并尽量标注语言，例如 ```js。',
  '不要把普通解释性段落误写成代码块；只有代码内容才放进 fenced code block。',
  '如果只是提到变量名、函数名、命令名或短表达式，使用单个反引号作为行内代码。',
  '当你输出代码块时，代码缩进一律使用 2 个空格，不要使用 4 个空格或 Tab。',
  '如果代码所属语言通常使用分号结尾，例如 JavaScript、TypeScript、Java、C、C++、C#、Go、PHP、Rust 等，语句结尾必须补上分号；不使用分号作为语法规范的语言除外，例如 Python、Ruby、Shell。',
].join('\n');

export const GREETING_PATTERNS = [/^你好[呀啊]?$/, /^hello$/i, /^hi$/i, /^嗨$/, /^在吗$/];

export const RESUME_REQUEST_PATTERN =
  /(优化|修改|润色|完善|评审|点评|改写|看看|review|重写|调整).{0,8}简历|简历.{0,8}(优化|修改|润色|完善|评审|点评|改写|看看|review|重写|调整)/i;
export const PROJECT_HIGHLIGHT_PATTERN =
  /(项目亮点|项目经验|项目描述).{0,8}(挖掘|提炼|优化|润色|改写|突出)|如何挖掘简历项目亮点/;
export const SELF_INTRO_PATTERN = /(面试|前端).{0,8}自我介绍|自我介绍.{0,8}(面试|前端)/;
export const TECHNICAL_COMPARE_PATTERN = /(区别|差异|对比|比较|不同|选哪个|怎么选|vs|VS|versus)/;
export const TECHNICAL_MECHANISM_PATTERN =
  /(原理|机制|流程|顺序|过程|底层|工作方式|如何工作|怎么工作|如何执行|怎么执行|实现方式|实现原理|为什么会)/;
export const TECHNICAL_QUESTION_PATTERN =
  /(什么是|是什么|啥是|含义|作用|用途|区别|差异|对比|比较|原理|机制|流程|顺序|过程|为什么|如何|怎么|讲讲|解释|介绍|解析)/;
export const TECHNICAL_DOMAIN_HINTS = [
  'javascript',
  'js',
  'typescript',
  'ts',
  'react',
  'vue',
  'node',
  'nodejs',
  'html',
  'css',
  'webpack',
  'vite',
  'babel',
  'esbuild',
  'rollup',
  'pnpm',
  'npm',
  'yarn',
  'http',
  'https',
  'tcp',
  'udp',
  'graphql',
  'rest',
  'jwt',
  'cookie',
  'session',
  'promise',
  'async',
  'await',
  'hook',
  'hooks',
  'usememo',
  'usecallback',
  'useeffect',
  'usestate',
  'usecontext',
  'memo',
  'fiber',
  'diff',
  'virtualdom',
  '虚拟dom',
  '闭包',
  '事件循环',
  '原型链',
  'this',
  '原型',
  '继承',
  '响应式',
  '依赖收集',
  '缓存',
  '协商缓存',
  '强缓存',
  '跨域',
  '同源策略',
  '浏览器',
  '渲染',
  '重排',
  '重绘',
  '微任务',
  '宏任务',
  '工程化',
  '性能',
  '防抖',
  '节流',
  '状态管理',
  '组件通信',
  'tree shaking',
  'treeshaking',
];
export const TECHNICAL_MECHANISM_HINTS = [
  '事件循环',
  '微任务',
  '宏任务',
  '原型链',
  '响应式',
  '依赖收集',
  '虚拟dom',
  'virtualdom',
  'fiber',
  '浏览器渲染',
  '渲染流程',
  '垃圾回收',
  '协商缓存',
  '强缓存',
  '同源策略',
  '跨域',
];
export const SECTION_HINTS = [
  '教育背景',
  '专业技能',
  '工作经历',
  '项目经验',
  '实习经历',
  '校园经历',
  '技能总结',
  '自我评价',
  '工作项目',
  '项目背景',
];
export const HORIZONTAL_RULE_PATTERN = /^\s{0,3}(?:-{3,}|\*{3,}|_{3,})\s*$/;
