import type { InterviewLevel, InterviewQuestion, InterviewTopic } from '@mianshitong/shared';

export const LEVEL_WEIGHT: Record<InterviewLevel, number> = {
  junior: 1,
  mid: 2,
  senior: 3,
};

export const TOPIC_ORDER: InterviewTopic[] = [
  'javascript',
  'react',
  'vue',
  'engineering',
  'performance',
  'network',
  'security',
  'node',
  'frontend',
];

export const QUESTION_BANK: InterviewQuestion[] = [
  {
    id: 'js_event_loop',
    topic: 'javascript',
    level: 'mid',
    title: '事件循环与任务调度',
    prompt: '请你讲一下浏览器事件循环里宏任务和微任务的执行顺序，并给一个会让初学者困惑的例子。',
    keyPoints: ['调用栈', '宏任务', '微任务', 'Promise', '执行顺序'],
    followUps: ['Node.js 里的 nextTick 和 Promise 微任务顺序有什么差异？'],
  },
  {
    id: 'js_closure_memory',
    topic: 'javascript',
    level: 'mid',
    title: '闭包与内存',
    prompt: '闭包为什么会导致内存长期不释放？在真实项目里你怎么规避闭包引发的泄漏？',
    keyPoints: ['作用域链', '引用关系', '定时器', '事件监听', '清理策略'],
    followUps: ['如果是 React 组件里的闭包过期问题，你会怎么定位？'],
  },
  {
    id: 'react_render',
    topic: 'react',
    level: 'mid',
    title: '渲染与状态更新',
    prompt: 'React 状态更新为什么看起来不是立刻生效？请你结合批处理和函数式更新解释一下。',
    keyPoints: ['批处理', '异步更新', '函数式更新', '闭包陷阱', '重渲染'],
    followUps: ['React 19 下你如何判断某段逻辑应该放在 state 还是 memo 里？'],
  },
  {
    id: 'react_performance',
    topic: 'react',
    level: 'senior',
    title: 'React 性能优化路径',
    prompt: '如果一个页面交互卡顿，你会如何分层排查 React 性能问题？请给出具体工具与步骤。',
    keyPoints: ['性能分析', 'Profiler', '渲染次数', 'memo', '拆分组件'],
    followUps: ['如果是列表渲染慢，你会优先做哪两件事，为什么？'],
  },
  {
    id: 'vue_reactivity',
    topic: 'vue',
    level: 'mid',
    title: 'Vue 响应式原理',
    prompt: 'Vue3 的响应式系统是如何追踪依赖并触发更新的？请讲讲 effect 和 scheduler 的作用。',
    keyPoints: ['Proxy', '依赖收集', 'effect', 'scheduler', '触发更新'],
    followUps: ['为什么说 computed 本质上是带缓存的 effect？'],
  },
  {
    id: 'engineering_ci',
    topic: 'engineering',
    level: 'mid',
    title: '工程化与质量保障',
    prompt: '你会如何设计前端项目的 CI 流水线，保证迭代速度和发布质量？',
    keyPoints: ['lint', 'typecheck', 'test', '构建', '回滚策略'],
    followUps: ['如果 CI 很慢，你会如何定位瓶颈并优化？'],
  },
  {
    id: 'engineering_monitoring',
    topic: 'engineering',
    level: 'senior',
    title: '可观测性',
    prompt: '前端线上可观测性你会怎么做？请覆盖日志、指标、链路与告警。',
    keyPoints: ['日志', '指标', '告警', '埋点', '故障定位'],
    followUps: ['如何在隐私合规前提下采集前端监控数据？'],
  },
  {
    id: 'perf_web_vitals',
    topic: 'performance',
    level: 'mid',
    title: 'Web Vitals 实战',
    prompt: '你如何解释 LCP、INP、CLS，并在项目中做持续优化？',
    keyPoints: ['LCP', 'INP', 'CLS', '性能预算', '持续监控'],
    followUps: ['如果 LCP 波动很大，你会优先排查哪些资源？'],
  },
  {
    id: 'network_http_cache',
    topic: 'network',
    level: 'mid',
    title: 'HTTP 缓存策略',
    prompt: '请说明强缓存与协商缓存的区别，并给出静态资源版本化方案。',
    keyPoints: ['Cache-Control', 'ETag', 'Last-Modified', '版本号', '命中率'],
    followUps: ['为什么有了 ETag 仍然要考虑 Cache-Control？'],
  },
  {
    id: 'network_https',
    topic: 'network',
    level: 'junior',
    title: 'HTTPS 基础',
    prompt: 'HTTPS 比 HTTP 多了哪些关键步骤，为什么能更安全？',
    keyPoints: ['TLS 握手', '证书', '非对称加密', '会话密钥', '完整性'],
    followUps: ['如果证书过期，浏览器会怎样处理？'],
  },
  {
    id: 'security_xss_csrf',
    topic: 'security',
    level: 'mid',
    title: 'XSS 与 CSRF',
    prompt: '请对比 XSS 和 CSRF 的攻击方式与防御手段，并说明前端该做什么。',
    keyPoints: ['攻击面', '输入校验', '转义', 'Token', 'SameSite'],
    followUps: ['前端框架默认机制是否能完全阻止 XSS？'],
  },
  {
    id: 'node_stream',
    topic: 'node',
    level: 'mid',
    title: 'Node 流与背压',
    prompt: 'Node.js 里的 Stream 背压是什么，为什么能降低内存峰值？',
    keyPoints: ['stream', 'backpressure', 'highWaterMark', 'pipe', '内存'],
    followUps: ['如果下游消费速度持续慢于上游，会发生什么？'],
  },
];
